slider_mapping:
  0: master  # Master channel
  1: youtube-music-desktop-app
  2: firefox
  3: brightness_script  # Path of Exile application

button_mapping:
  0: button1
  1: button2

# Set this to true if you want the controls inverted
invert_sliders: false

# Settings for connecting to the Arduino board
com_port: /dev/ttyS0fake1  # COM port for the Arduino Uno
baud_rate: 9600  # Baud rate for serial communication

# Adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad hardware)
noise_reduction: default

# Analog slider values and their mapping range
analog_slider_min_values:
  0: 0
  1: 30
  2: 0
  3: 0

analog_slider_max_values:
  0: 1023
  1: 1023
  2: 1023
  3: 1023